server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: UserManagement
          uri: http://localhost:8082
          predicates:
            - Path=/users/**, /userLoginStatuses/**
        - id: ApplicationProcessing
          uri: http://localhost:8083
          predicates:
            - Path=/applications/**, /applicationSummaries/**
        - id: documentandnotification
          uri: http://localhost:8084
          predicates:
            - Path=/notifications/**, /resultDocuments/**, /notificationSummaries/**, /resultDocumentSummaries/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: UserManagement
          uri: http://userManagement:8080
          predicates:
            - Path=/users/**, 
        - id: ApplicationProcessing
          uri: http://applicationProcessing:8080
          predicates:
            - Path=/applications/**, 
        - id: documentandnotification
          uri: http://documentandnotification:8080
          predicates:
            - Path=/notifications/**, /resultDocuments/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
