---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: UserManagement
  labels:
    app: UserManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: UserManagement
  template:
    metadata:
      labels:
        app: UserManagement
    spec:
      containers:
        - name: UserManagement
          image: username/UserManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ApplicationProcessing
  labels:
    app: ApplicationProcessing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ApplicationProcessing
  template:
    metadata:
      labels:
        app: ApplicationProcessing
    spec:
      containers:
        - name: ApplicationProcessing
          image: username/ApplicationProcessing:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentandnotification
  labels:
    app: documentandnotification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: documentandnotification
  template:
    metadata:
      labels:
        app: documentandnotification
    spec:
      containers:
        - name: documentandnotification
          image: username/documentandnotification:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: UserManagement
  labels:
    app: UserManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: UserManagement


---


apiVersion: v1
kind: Service
metadata:
  name: ApplicationProcessing
  labels:
    app: ApplicationProcessing
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ApplicationProcessing


---


apiVersion: v1
kind: Service
metadata:
  name: documentandnotification
  labels:
    app: documentandnotification
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: documentandnotification

