apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentandnotification
  labels:
    app: documentandnotification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: documentandnotification
  template:
    metadata:
      labels:
        app: documentandnotification
    spec:
      containers:
        - name: documentandnotification
          image: "username/documentandnotification:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
