apiVersion: v1
kind: Service
metadata:
  name: documentandnotification
  labels:
    app: documentandnotification
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: documentandnotification